// Test generated by RoostGPT for test practice-go-nasacollage using AI Type Azure Open AI and AI Model roost-gpt4-32k

package collage

import (
	"testing"
)

func TestHighIndex(t *testing.T) {
	testCases := []struct {
		name           string
		barGraph       BarGraph
		expectedResult int
	}{
		{
			name:           "Test with an empty BarGraph",
			barGraph:       BarGraph{},
			expectedResult: -1,
		},
		{
			name:           "Test with a single element BarGraph",
			barGraph:       BarGraph{{H: 1}},
			expectedResult: 0,
		},
		{
			name:           "Test with multiple element BarGraph where all bars have the same height",
			barGraph:       BarGraph{{H: 1}, {H: 1}, {H: 1}},
			expectedResult: 0,
		},
		{
			name:           "Test with multiple element BarGraph where one bar has the highest height",
			barGraph:       BarGraph{{H: 1}, {H: 2}, {H: 1}},
			expectedResult: 1,
		},
		{
			name:           "Test with multiple element BarGraph where multiple bars have the same highest height",
			barGraph:       BarGraph{{H: 2}, {H: 1}, {H: 2}},
			expectedResult: 0,
		},
		// Add more test cases here
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			res := tc.barGraph.HighIndex()
			if res != tc.expectedResult {
				t.Fatalf("expected %d, but got %d", tc.expectedResult, res)
			}
		})
	}
}
